# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: S M Sotirov Articles site.
email: s.m.sotirov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains set of articles mainly on IT topics, collected from around the internet. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smsotirov.com" # the base hostname & protocol for your site
# twitter_username: smsotirov
github_username:  smsotirov
google_plus_username:  "Сотир Сотиров"

# Build settings
markdown: kramdown
